ARG BUILD_FROM=ghcr.io/hassio-addons/base:21.0.0

FROM ${BUILD_FROM}

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setup base
ARG NGINX_PROXY_MANAGER_VERSION="v2.15.1"

# hadolint ignore=DL3003
COPY scripts/patch-npm.py /tmp/patch-npm.py
RUN \
    apk add --no-cache --upgrade libcrypto3 libssl3 openssl openssl-dev certbot \
    \
    && apk add --no-cache \
        apache2-utils=2.4.67-r0 \
        libcap=2.78-r0 \
        logrotate=3.22.0-r0 \
        nginx-mod-stream=1.30.2-r1 \
        nginx=1.30.2-r1 \
        nodejs=24.16.0-r0 \
        npm=11.12.1-r0 \
        py3-pip=26.1.2-r0 \
        python3=3.14.5-r0 \
        yarn=1.22.22-r1 \
    \
    && apk add --no-cache --virtual .build-dependencies \
        build-base=0.5-r4 \
        git=2.54.0-r0 \
        libffi-dev=3.5.2-r1 \
        python3-dev=3.14.5-r0 \
    \
    \
    && curl -J -L -o /tmp/nginxproxymanager.tar.gz \
        "https://github.com/NginxProxyManager/nginx-proxy-manager/archive/${NGINX_PROXY_MANAGER_VERSION}.tar.gz" \
    && mkdir /app \
    && tar zxvf \
        /tmp/nginxproxymanager.tar.gz \
        --strip 1 -C /app \
    \
    && cd /app \
    \
    && python3 /tmp/patch-npm.py --dir /app \
    \
    && cd /app/frontend \
    && yarn install --ignore-engines --network-timeout 100000 \
    && yarn locale-compile \
    && yarn build \
    && rm -rf node_modules \
    \
    && mkdir -p /opt/nginx-proxy-manager/frontend \
    && cp -r /app/frontend/dist/. /opt/nginx-proxy-manager/frontend/ \
    \
    && cd /app/backend \
    && yarn install \
    && rm -rf node_modules \
    && cp -r /app/backend/. /opt/nginx-proxy-manager/ \
    \
    && cd /opt/nginx-proxy-manager \
    && yarn install \
    && rm -rf /etc/services.d/frontend \
    && rm -rf /opt/nginx-proxy-manager/config \
    \
    && rm -f -r /etc/nginx \
    && cp -r /app/docker/rootfs/etc/nginx /etc/nginx \
    && rm -f /etc/nginx/conf.d/dev.conf \
    \
    && cp /app/docker/rootfs/etc/logrotate.d/nginx-proxy-manager /etc/logrotate.d \
    \
    && mkdir -p \
        /run/nginx \
    \
    && npx --yes clean-modules --yes --no-defaults --keep-empty --directory /opt/nginx-proxy-manager \
    && yarn cache clean \
    \
    && apk del --purge .build-dependencies \
    \
    && rm -f -r \
        /app \
        /etc/init.d/nginx \
        /etc/logrotate.d/nginx \
        /opt/nginx-proxy-manager/node_modules/bcrypt/build \
        /root/.cache \
        /root/.node-gyp \
        /tmp/.![.]* \
        /tmp/* \
        /usr/lib/node_modules \
        /usr/local/share/.cache \
        /var/lib/nginx \
        /var/log/nginx \
        /var/tmp/nginx \
        /var/www

# Copy root filesystem
COPY rootfs /

# Build arguments
ARG BUILD_ARCH
ARG BUILD_DATE
ARG BUILD_DESCRIPTION
ARG BUILD_NAME
ARG BUILD_REF
ARG BUILD_REPOSITORY
ARG BUILD_VERSION

# Labels
LABEL \
    io.hass.name="${BUILD_NAME}" \
    io.hass.description="${BUILD_DESCRIPTION}" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION} \
    maintainer="Konstantin Ekimovskii" \
    org.opencontainers.image.title="${BUILD_NAME}" \
    org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
    org.opencontainers.image.vendor="Konstantin Ekimovskii" \
    org.opencontainers.image.authors="Konstantin Ekimovskii" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://addons.community" \
    org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.revision=${BUILD_REF} \
    org.opencontainers.image.version=${BUILD_VERSION}
